sudo: required
language: scala
scala:
  - 2.12.4
jdk:
  - oraclejdk8
services:
  - docker

before_install:
  - docker pull redis:4-alpine
  - docker run --name redis -d -p 6379:6379 redis:4-alpine
  - docker ps -a

before_script:
  - sleep 3

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

script:
  - sbt clean test +package

after_success:
  - test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_TAG}" != '' && sbt +publish
